# Generated by Django 3.1.6 on 2021-03-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_value_currency',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
