# Generated by Django 3.1.6 on 2021-04-08 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_file_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(blank=True, default='In Progress', max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='invoice_files',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_files',
            field=models.FileField(blank=True, null=True, upload_to='job_files/'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_notes',
            field=models.TextField(default='Please add some notes about this job'),
        ),
        migrations.AddField(
            model_name='job',
            name='purchase_orders',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/'),
        ),
        migrations.AddField(
            model_name='job',
            name='receipts',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobstatus', to_field='job_status'),
        ),
    ]
