export const GET_JOBS = "GET_JOBS";
export const PUT_JOB = "PUT_JOB";
export const GET_ERRORS = "GET_ERRORS";
export const GET_COMPANIES = "GET_COMPANIES";
export const ADD_COMPANY= "ADD_COMPANY";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEES";
export const PUT_EMPLOYEE = "PUT_EMPLOYEE";
export const FORM_EMPLOYEE_UPDATE = "FORM_EMPLOYEE_UPDATE";
export const ADD_JOB = "ADD_JOB";
export const GET_MESSAGES = "GET_MESSAGES";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT SUCCESS";
export const CLEAR_JOBS = "CLEAR_JOBS";
export const DELETE_JOB = "DELETE_JOBS";
export const EMPLOYEE_ID = "EMPLOYEE_ID";
export const OPEN_EMPLOYEE_DETAIL_FROM = "OPEN_EMPLOYEE_DETAIL_FROM";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const OPEN_EMPLOYEE_DELETE_FROM = "OPEN_EMPLOYEE_DELETE_FROM";
export const OPEN_EMPLOYEE_CREATE_FROM = "OPEN_EMPLOYEE_CREATE_FROM";
export const GET_GENDER = "GET_GENDER";
export const GET_RELATIONSHIPSTATUS = "GET_RELATIONSHIPSTATUS";
export const CHECKBOX_CHANGE = "CHECKBOX_CHANGE";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";
export const USERNAME_CHANGE = "USERNAME_CHANGE";
export const OPEN_COMPANY_CREATE_FROM = "OPEN_COMPANY_CREATE_FROM";
export const COMPANY_ID = "COMPANY_ID";
export const PUT_COMPANY = "PUT_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const OPEN_COMPANY_DELETE_FROM = "OPEN_COMPANY_DELETE_FROM";
export const OPEN_COMPANY_DETAIL_FROM = "OPEN_COMPANY_DETAIL_FROM";
export const OPEN_NEW_JOB_FORM = "OPEN_NEW_JOB_FORM";
export const JOB_NAME_CHANGE_NEW_JOB_FORM = "JOB_NAME_CHANGE_NEW_JOB_FORM";
export const JOB_NEW_JOB_FROM_SUBMITTED = "JOB_NEW_JOB_FROM_SUBMITTED"
export const JOB_VALUE_CHANGE_NEW_JOB_FORM = "JOB_VALUE_CHANGE_NEW_JOB_FORM"
export const JOB_STATUS_CHANGE_NEW_JOB_FORM = "JOB_STATUS_CHANGE_NEW_JOB_FORM"
export const JOB_DATE_CHANGE_NEW_JOB_FORM = "JOB_DATE_CHANGE_NEW_JOB_FORM"
export const JOB_COMPANY_CHANGE_NEW_JOB_FORM = "JOB_COMPANY_CHANGE_NEW_JOB_FORM"
export const JOB_EMPLOYEE_CHANGE_NEW_JOB_FORM = "JOB_EMPLOYEE_CHANGE_NEW_JOB_FORM"
export const JOB_NOTES_CHANGE_NEW_JOB_FORM = "JOB_NOTES_CHANGE_NEW_JOB_FORM"
export const JOB_FORM_CLEAR = "JOB_FORM_CLEAR"
export const SEARCH_PROJECTS = "SEARCH_PROJECTS"
export const OPEN_EDIT_JOB_FORM = "OPEN_EDIT_JOB_FORM"
export const SET_PROJECT_ID = "SET_PROJECT_ID"
export const CLEAR_PROJECT_ID = "CLEAR_PROJECT_ID"
export const SET_FORM_DATA = "SET_FORM_DATA"








