# Generated by Django 3.1.6 on 2021-03-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('companyname', models.CharField(max_length=200)),
                ('jobtitle', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('mobile', models.CharField(max_length=200)),
            ],
        ),
    ]
